name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '^1.16'
      - name: Build
        run: make all
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/darwin/htmltoebook-darwin.tar.gz
            out/windows/htmltoebook-windows.zip
            out/linux/htmltoebook-linux.tar.gz
          body_path: changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}